/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schedulersimulator;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HenriqueLinhares
 */
public class OutputFileWriter {

    private static final String outputFileName = "output.txt";

    private static File outputFile = new File(OutputFileWriter.outputFileName);

    private static FileWriter filewriter;

    private static BufferedWriter bwriter;

    public static void setup() throws IOException {

        // if file doesnt exists, then create it
        if (!OutputFileWriter.outputFile.exists()) {
            OutputFileWriter.outputFile.createNewFile();
        }

        OutputFileWriter.filewriter = new FileWriter(OutputFileWriter.outputFile.getAbsoluteFile());
        OutputFileWriter.bwriter = new BufferedWriter(OutputFileWriter.filewriter);

        OutputFileWriter.bwriter.write("#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.write("$$$$$  <  Scheduling Report  >   $$$$$");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.write("#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.newLine();

    }
    
    public static void writeTaskEnteringProcessorEvent(Task T, int time){
       
        try {
            OutputFileWriter.bwriter.newLine();
            OutputFileWriter.bwriter.write("The Task named "+T.getName()+" entered the processor at the time "+time);
            OutputFileWriter.bwriter.newLine();
        } catch (IOException ex) {
           ErrorSender.errorWritingTaskInfoIntoReport();
        }
   
    }
    
    
    public static void writeTaskLeavingProcessorEvent(Task T, int time){
       
        try {
            OutputFileWriter.bwriter.newLine();
            OutputFileWriter.bwriter.write("The Task named "+T.getName()+" have left the processor at the time "+time);
            OutputFileWriter.bwriter.newLine();
        } catch (IOException ex) {
           ErrorSender.errorWritingTaskInfoIntoReport();
        }
   
    }
    
    
    
    

    public static void close() {
        try {
        OutputFileWriter.bwriter.newLine();    
        OutputFileWriter.bwriter.write("#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.write("Report generated by SchedulerSimulator");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.write("Developers team: Henrique Linhares, Raphael Quintanilha, Diogo Souza and Fabrizio Moura.");
        OutputFileWriter.bwriter.newLine();
        OutputFileWriter.bwriter.write("Universidade Federal Fluminense");
        
            OutputFileWriter.bwriter.close();
        } catch (IOException ex) {
            ErrorSender.errorClosingOutputFile();
        }
    }

}
